Repository IncPlusPlus/betterstat-server, pull requests merged in 2020-05, with the labels that each got.

#175 Add GitHub actions
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-management.yml
Labels: chore

#178 Add FOSSA and Codecov
  .travis.yml
  pom.xml
  src/test/java/io/github/incplusplus/thermostat/test/DummyTest.java
Labels: chore

#179 Add a crap ton of badges
  README.md
Labels: chore

#181 Create LICENSE
  LICENSE
Labels: chore

#182 Add license scan badge
  JSON Schemas/SampleNode.JSON
  JSON Schemas/ServerConfig.JSON
  README.md
Labels: chore

#184 Move FOSSA into the after_success phase
  .travis.yml
Labels: chore

#117 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: security fix

#186 Use HTTPS when retrieving artifacts from Spring milestones repo
  pom.xml
Labels: chore

#187 Update master
  pom.xml
Labels: ignore-master-sync

#189 Added DepShield badge!
  README.md
Labels: chore

#190 Quick master refresh
  README.md
Labels: ignore-master-sync

#191 Update Maven enforcer plugin
  pom.xml
Labels: chore
